id: medcom.fhir.dk.homecareobservation
canonical: http://medcomfhir.dk/ig/homecareobservation
name: MedComHomeCareObservation
title: MedCom HomeCareObservation
description: Communication between general practitioners and municipal acute care team.
status: draft # draft | active | retired | unknown
version: 1.1.1-trial-use
fhirVersion: 4.0.1 # https://www.hl7.org/fhir/valueset-FHIR-version.html
copyrightYear: 2023+
releaseLabel: trial-use # ci-build | draft | qa-preview | ballot | trial-use | release | update | normative+trial-use
jurisdiction: urn:iso:std:iso:3166#DK "Denmark"
publisher:
  name: MedCom
  url: http://www.medcom.dk
  email: fhir@medcom.dk

dependencies:
  hl7.fhir.dk.core: 3.4.0
  medcom.fhir.dk.terminology: 2.0.0-draft
  medcom.fhir.dk.core: 2.4.0
  medcom.fhir.dk.messaging: 3.0.0
  medcom.fhir.dk.messagedefinitions: 1.0.1-trial-use
  
menu:
  Home: index.html
  Profiles: profiles.html
  Extensions: extensions.html
  Artifacts: artifacts.html
  More:
    Table of Contents: toc.html
    Downloads: downloads.html
    Dependencies: dependencies.html

parameters:
  apply-version: false
  default-version: true
  apply-publisher: false
  default-publisher: true
  pin-canonicals: pin-multiples
  excludettl: true
